const PDFDocument = require('pdfkit');

class PerPersonReportGenerator {
  constructor(staff, month, year, data) {
    this.staff = staff;
    this.month = month;
    this.year = year;
    this.data = data;
    this.doc = new PDFDocument({ size: 'A4', margin: 50 });
  }

  generate() {
    this.addCoverPage();
    this.addSummaryPage();
    this.addDetailsPage();
    this.addSignaturePage();
    
    this.doc.end();
    return this.doc;
  }

  addCoverPage() {
    const { doc, staff, month, year } = this;
    const monthName = new Date(year, month - 1).toLocaleString('default', { month: 'long' });

    // Background decoration
    doc.rect(0, 0, doc.page.width, doc.page.height).fill('#f0fdf4');
    
    doc.fillColor('#16a34a').fontSize(40).font('Helvetica-Bold')
       .text('RESEARCH PERFORMANCE', 50, 250, { align: 'center' });
    doc.fontSize(20).fillColor('#1f2937')
       .text('MONTHLY MATRIX REPORT', 50, 300, { align: 'center' });

    doc.moveTo(100, 350).lineTo(doc.page.width - 100, 350).strokeColor('#16a34a').lineWidth(2).stroke();

    doc.fontSize(24).fillColor('#16a34a').font('Helvetica-Bold')
       .text(`Dr. ${staff.name}`, 50, 400, { align: 'center' });
    doc.fontSize(16).fillColor('#6b7280').font('Helvetica')
       .text(`${staff.department} Department`, 50, 435, { align: 'center' });

    doc.fontSize(18).fillColor('#1f2937').font('Helvetica-Bold')
       .text(`${monthName} ${year}`, 50, 500, { align: 'center' });

    doc.fontSize(10).fillColor('#9ca3af')
       .text('Generated by JJCET CFRD Research Portal', 0, 750, { align: 'center' });
  }

  addSummaryPage() {
    const { doc, data } = this;
    doc.addPage({ size: 'A4', margin: 50 });
    doc.rect(0, 0, doc.page.width, doc.page.height).fill('#ffffff');

    doc.fillColor('#16a34a').fontSize(24).font('Helvetica-Bold').text('Executive Summary', 50, 50);
    doc.moveTo(50, 85).lineTo(doc.page.width - 50, 85).strokeColor('#e5e7eb').lineWidth(1).stroke();

    // Stats Grid
    const stats = this.calculateStats();
    let y = 120;
    const boxWidth = 230;
    const boxHeight = 100;

    const drawBox = (title, value, x, y, color) => {
      doc.rect(x, y, boxWidth, boxHeight).fill(`${color}10`);
      doc.rect(x, y, 5, boxHeight).fill(color);
      doc.fillColor(color).fontSize(10).font('Helvetica-Bold').text(title.toUpperCase(), x + 20, y + 25);
      doc.fillColor('#1f2937').fontSize(32).font('Helvetica-Bold').text(value, x + 20, y + 45);
    };

    drawBox('Research Papers', stats.papers, 50, y, '#3b82f6');
    drawBox('Funded Projects', stats.projects, 300, y, '#10b981');
    y += 120;
    drawBox('Patents Filed', stats.patents, 50, y, '#f59e0b');
    drawBox('Books Published', stats.books, 300, y, '#ef4444');
    y += 120;
    drawBox('Others / General', stats.others, 50, y, '#8b5cf6');
    drawBox('Submission Streak', `${stats.streak} Days`, 300, y, '#ec4899');

    // Chart area placeholder (textual)
    y += 150;
    doc.fillColor('#1f2937').fontSize(14).font('Helvetica-Bold').text('Monthly Activity Distribution', 50, y);
    doc.fontSize(10).font('Helvetica').fillColor('#6b7280').text('Analysis based on daily research workload submissions.', 50, y + 20);
  }

  addDetailsPage() {
    const { doc, data } = this;
    doc.addPage({ size: 'A4', margin: 50 });

    doc.fillColor('#16a34a').fontSize(20).font('Helvetica-Bold').text('Detailed Activity Log', 50, 50);
    
    // Table Header
    let y = 90;
    doc.rect(50, y, doc.page.width - 100, 25).fill('#16a34a');
    doc.fillColor('#ffffff').fontSize(10).font('Helvetica-Bold');
    doc.text('Date', 60, y + 8);
    doc.text('Activity Description', 140, y + 8);
    doc.text('Status', 480, y + 8);

    y += 25;
    doc.fillColor('#1f2937').font('Helvetica');

    data.forEach((item, index) => {
      if (y > 700) {
        doc.addPage();
        y = 50;
        // Re-draw header
        doc.rect(50, y, doc.page.width - 100, 25).fill('#16a34a');
        doc.fillColor('#ffffff').fontSize(10).font('Helvetica-Bold');
        doc.text('Date', 60, y + 8);
        doc.text('Activity Description', 140, y + 8);
        doc.text('Status', 480, y + 8);
        y += 25;
      }

      const dateStr = new Date(item.date).toLocaleDateString('en-GB');
      const description = item.activityTitle || item.paperTitle || item.projectName || item.patentTitle || item.bookTitle || 'General Research Work';
      const status = item.status.toUpperCase();

      doc.fillColor(index % 2 === 0 ? '#ffffff' : '#f9fafb').rect(50, y, doc.page.width - 100, 30).fill();
      doc.fillColor('#1f2937').fontSize(9);
      doc.text(dateStr, 60, y + 10);
      doc.text(description, 140, y + 10, { width: 320, lineBreak: false });
      
      const statusColor = status === 'APPROVED' ? '#16a34a' : status === 'PENDING' ? '#f59e0b' : '#ef4444';
      doc.fillColor(statusColor).font('Helvetica-Bold').text(status, 480, y + 10);
      doc.font('Helvetica');

      y += 30;
    });
  }

  addSignaturePage() {
    const { doc } = this;
    doc.addPage({ size: 'A4', margin: 50 });

    doc.fillColor('#16a34a').fontSize(20).font('Helvetica-Bold').text('Verification & Approval', 50, 50);
    doc.fontSize(10).font('Helvetica').fillColor('#6b7280')
       .text('This report is digitally generated based on the submissions approved by the CFRD department.', 50, 80);

    const sigY = 600;
    doc.strokeColor('#d1d5db').lineWidth(1).moveTo(50, sigY).lineTo(200, sigY).stroke();
    doc.strokeColor('#d1d5db').lineWidth(1).moveTo(doc.page.width - 200, sigY).lineTo(doc.page.width - 50, sigY).stroke();

    doc.fillColor('#1f2937').fontSize(11).font('Helvetica-Bold');
    doc.text('Staff Member Signature', 50, sigY + 15);
    doc.text('Director - CFRD', doc.page.width - 200, sigY + 15, { align: 'right' });

    doc.fontSize(9).font('Helvetica').fillColor('#9ca3af')
       .text('JJ College of Engineering and Technology - Center for Research and Development', 0, 780, { align: 'center' });
  }

  calculateStats() {
    const stats = { papers: 0, projects: 0, patents: 0, books: 0, others: 0, streak: 0 };
    this.data.forEach(item => {
      if (item.paperTitle) stats.papers++;
      else if (item.projectName) stats.projects++;
      else if (item.patentTitle) stats.patents++;
      else if (item.bookTitle) stats.books++;
      else stats.others++;
    });
    // Simplified streak count from data
    stats.streak = this.data.length; 
    return stats;
  }
}

module.exports = PerPersonReportGenerator;
